name: Run Python Test

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Run test script
        run: python test_runner.py
